# Neural Network

$f=$ activation function

$W=$ weight matrix

$I=$ input matrix

$\hat{y}=W_3 x f(W_2 x f(W_1xI)))$

$l(y,\hat{y})=$ loss function

In [154]:
import numpy as np
import sympy as sp
import pandas as pd
n_lag = 4
n_out = 3

hidden_layers = np.array([np.ones(x+1) for x in (10, 4)])

weights = np.random.rand(2,n_lag) #1. ziellänge, 2. input_vec

d = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
X_1 = pd.DataFrame(data=d)
d_y = {'col_y': [9, 10, 11]}
y_1 = pd.DataFrame(data=d_y)
X_1


#n_lag = number of neurons of previous layer
#n_out = number of neurons of output layer

col1  col2
0     1     4
1     2     5
2     3     6

In [172]:
s = [y_1.values]
s.append(y_1.values)
s

[array([[ 9],
        [10],
        [11]], dtype=int64), array([[ 9],
        [10],
        [11]], dtype=int64)]

In [128]:
x = sp.Symbol('x')
matrix = np.array([[2, 3, 4], [5, 6, 7]])
vec_m = np.array([[3, 3, 3], [2, 2, 2]])

expr = x * 3
#expr.subs(x, 2)
matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [105]:
matrix_2 = [[expr.subs(x, value) for value in row] for row in matrix]
matrix_2

[[6, 9, 12], [15, 18, 21]]

In [139]:
vec_m

array([[3, 3, 3],
       [2, 2, 2]])

In [178]:
#vec_m = np.reshape(vec_m, (-1, 1))
vec_new = vec_m.T
vec_new = np.insert(vec_new, vec_new.shape[0], np.array([[8, 4], [12, 11]]), axis=0)
vec_new

array([[ 3,  2],
       [ 3,  2],
       [ 3,  2],
       [ 8,  4],
       [12, 11]])

In [149]:
a = pd.DataFrame({"A": [1, 2], "B": [3, 4]}).to_numpy()
a

array([[1, 3],
       [2, 4]], dtype=int64)